#pragma once

#include <QObject>
#include <QSoundEffect>
#include <QTimer>
#include <QUrl>

class AlarmController;

/**
 * @brief Makes the alarm audible.
 *
 * The alarm state machine in AlarmController decided when a tone *should*
 * sound and nothing ever made one. This class is the missing half: it watches
 * that state machine and plays the burst that matches the highest active
 * priority, for as long as the condition stands.
 *
 * IEC 60601-1-8 governs what is played:
 *
 *  - **A burst per priority.** High priority is a burst of ten pulses, medium
 *    three, low one or two. The bursts themselves are generated by
 *    tools/audio/make_alarm_tones.py, which documents every parameter of the
 *    pulse - fundamental, harmonics, duration, rise time - against the windows
 *    the standard allows.
 *
 *  - **A burst interval per priority.** A burst repeats until the condition is
 *    dealt with. High repeats fastest because it means act now.
 *
 *  - **Audio paused and audio off are silence, not a lower volume.** Both are
 *    deliberate operator acts that AlarmController already models and
 *    time-limits, and this class simply follows `audioActive`.
 *
 * The volume follows the stored setting, with a floor: an alarm that can be
 * turned down to inaudible is an alarm that can be missed, so the setting
 * scales between a floor and full, never to zero.
 */
class AlarmAudio : public QObject
{
    Q_OBJECT

    /** True while a burst is being played or awaited. */
    Q_PROPERTY(bool sounding READ sounding NOTIFY soundingChanged)
    /** 0 to 100, as the settings screen shows it. */
    Q_PROPERTY(int volume READ volume WRITE setVolume NOTIFY volumeChanged)
    /** False when no output device accepted the tone. */
    Q_PROPERTY(bool available READ available NOTIFY availableChanged)

public:
    explicit AlarmAudio(AlarmController *alarms, QObject *parent = nullptr);

    bool sounding() const;
    int volume() const;
    bool available() const;

    /** The floor the volume setting scales from, as a percentage. */
    static int minimumVolumePercent();

public slots:
    void setVolume(int percent);

    /**
     * @brief Plays one pulse so the operator can hear that the speaker works.
     *
     * IEC 60601-1-8 expects the auditory alarm signal to be verifiable. This
     * is what the power-on check and the settings screen call.
     */
    void playTestTone();

signals:
    void soundingChanged();
    void volumeChanged();
    void availableChanged();

private:
    void refresh();
    void startBurst();
    void stopBurst();
    QSoundEffect *effectFor(const QString &priority);
    static int intervalFor(const QString &priority);

    AlarmController *m_alarms = nullptr;

    QSoundEffect m_high;
    QSoundEffect m_medium;
    QSoundEffect m_low;
    QSoundEffect m_test;

    QTimer m_repeat;
    QString m_playingPriority;
    int m_volume = 70;
    bool m_available = true;
};
